theme: jekyll-theme-cayman
title: zkye Online
description: Keep writing and Keep loving.

github_username: ET-yzk
paginate: 10

# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description: ":)"
sidebar-avatar: https://avatars.githubusercontent.com/u/59281333?v=4     # 你的大头贴，请使用绝对地址.如：/img/avatar.jpg

# Featured Tags
featured-tags: true
featured-condition-size: 1     # A tag will be featured if the size of it is more than this condition value

